include:
  - component: $CI_SERVER_FQDN/components/slsa/provenance-signer@0.1.1
    inputs:
      bundle_file: provenance.json
      job_name: push-assets-generate-provenance-log-get-sources
      stage: provenance
      target_artifact: $CI_PROJECT_DIR/build/logs/get_sources.log
  - component: $CI_SERVER_FQDN/components/slsa/provenance-signer@0.1.1
    inputs:
      bundle_file: provenance.json
      job_name: push-assets-generate-provenance-log-push
      stage: provenance
      target_artifact: $CI_PROJECT_DIR/build/logs/push-all.log
  
default:
  cache: []
  retry:
    max: 2
    when:
      - data_integrity_failure
      - job_execution_timeout
      - runner_configuration_error
      - runner_external_dependency_failure
      - runner_interrupted
      - runner_system_failure
      - scheduler_failure
      - stale_schedule
      - stuck_or_timeout_failure
      - unknown_failure

variables: &common_variables
  ARTIFACT_COMPRESSION_LEVEL: "slowest"
  CACHE_COMPRESSION_LEVEL: "slowest"
  FF_USE_FASTZIP: "1"
  RUNNER_GENERATE_ARTIFACTS_METADATA: true
  TRANSFER_METER_FREQUENCY: "2s"

stages:
  - update_assets
  - provenance

push-assets:
  image: fedora:43
  stage: update_assets
  rules:
    - if: $CI_PROJECT_NAMESPACE != "celenityy"
      when: never
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "pages"
      changes:
      - .gitlab-ci.yml
      - ublock/badlists.txt
      - ublock/dove/assets.dev.json
      - ublock/dove/assets.json
      - ublock/dove/filters.txt
      - ublock/dove/unbreak-js.txt
      - ublock/dove/unbreak-js-testing.txt
      - ublock/phoenix/assets.dev.json
      - ublock/phoenix/assets.json
      - ublock/phoenix/filters.txt
      - ublock/phoenix/quick-fixes.txt
      - ublock/titanium/assets.dev.json
      - ublock/titanium/assets.json
      - scripts/env.sh
      - scripts/env_common.sh
      - scripts/env_external.sh
      - scripts/env_helpers.sh
      - scripts/get_sources.sh
      - scripts/get_sources-cel.sh
      - scripts/prep.sh
      - scripts/push-assets.sh
      - scripts/push-assets-cel.sh
      - scripts/utilities.sh
      - scripts/versions.sh
  tags:
    - saas-linux-2xlarge-amd64
  variables:
    <<: *common_variables
  before_script:
    - sudo dnf update -y --refresh
  script:
    - set -euo pipefail
    - echo 'Preparing secrets...'
    - /bin/bash scripts/prep.sh
    - echo 'Downloading dependencies...'
    - /bin/bash -x scripts/get_sources.sh
    - echo 'Pushing assets to S3...'
    - /bin/bash -x scripts/push-assets.sh
  artifacts:
    untracked: false
    when: always
    access: all
    expire_in: "30 days"
    paths:
      - $CI_PROJECT_DIR/build/logs/get_sources.log
      - $CI_PROJECT_DIR/build/logs/push-all.log

push-assets-generate-provenance-log-get-sources:
  stage: provenance
  rules:
    - if: $CI_PROJECT_NAMESPACE != "celenityy"
      when: never
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "pages"
      changes:
      - .gitlab-ci.yml
      - ublock/badlists.txt
      - ublock/dove/assets.dev.json
      - ublock/dove/assets.json
      - ublock/dove/filters.txt
      - ublock/dove/unbreak-js.txt
      - ublock/dove/unbreak-js-testing.txt
      - ublock/phoenix/assets.dev.json
      - ublock/phoenix/assets.json
      - ublock/phoenix/filters.txt
      - ublock/phoenix/quick-fixes.txt
      - ublock/titanium/assets.dev.json
      - ublock/titanium/assets.json
      - scripts/env.sh
      - scripts/env_common.sh
      - scripts/env_external.sh
      - scripts/env_helpers.sh
      - scripts/get_sources.sh
      - scripts/get_sources-cel.sh
      - scripts/prep.sh
      - scripts/push-assets.sh
      - scripts/push-assets-cel.sh
      - scripts/utilities.sh
      - scripts/versions.sh
  needs:
    - job: push-assets
      optional: false

push-assets-generate-provenance-log-push:
  stage: provenance
  rules:
    - if: $CI_PROJECT_NAMESPACE != "celenityy"
      when: never
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "pages"
      changes:
      - .gitlab-ci.yml
      - ublock/badlists.txt
      - ublock/dove/assets.dev.json
      - ublock/dove/assets.json
      - ublock/dove/filters.txt
      - ublock/dove/unbreak-js.txt
      - ublock/dove/unbreak-js-testing.txt
      - ublock/phoenix/assets.dev.json
      - ublock/phoenix/assets.json
      - ublock/phoenix/filters.txt
      - ublock/phoenix/quick-fixes.txt
      - ublock/titanium/assets.dev.json
      - ublock/titanium/assets.json
      - scripts/env.sh
      - scripts/env_common.sh
      - scripts/env_external.sh
      - scripts/env_helpers.sh
      - scripts/get_sources.sh
      - scripts/get_sources-cel.sh
      - scripts/prep.sh
      - scripts/push-assets.sh
      - scripts/push-assets-cel.sh
      - scripts/utilities.sh
      - scripts/versions.sh
  needs:
    - job: push-assets
      optional: false
