# celenity assets common environment variables

## CAUTION: Do NOT source this directly!
## Source 'env.sh' instead.

## Additionally, if you need to override any variables here, export them to your shell manually or use `env_override.sh`.
## Do NOT edit this file directly.

# celenity assets

# Scripts directory
readonly CEL_ASSETS_SCRIPTS="${CEL_ASSETS_ROOT}/scripts"
export CEL_ASSETS_SCRIPTS

# Set our platform, OS, and architecture
readonly CEL_ASSETS_ENV_HELPERS="${CEL_ASSETS_SCRIPTS}/env_helpers.sh"
export CEL_ASSETS_ENV_HELPERS
source "${CEL_ASSETS_ENV_HELPERS}"

# Do not use the system PATH
unset PATH

# If variables are defined with a custom `env_override.sh` file (located at the root project directory), let's use those
## These need to be set first, to ensure that they don't interfere with certain variables
readonly CEL_ASSETS_ENV_OVERRIDE="${CEL_ASSETS_ROOT}/env_override.sh"
if [[ -f "${CEL_ASSETS_ENV_OVERRIDE}" ]]; then
  source "${CEL_ASSETS_ENV_OVERRIDE}"
fi

## celenity assets utilities
readonly CEL_ASSETS_UTILS="${CEL_ASSETS_SCRIPTS}/utilities.sh"
export CEL_ASSETS_UTILS

# Configuration files
readonly CEL_ASSETS_CONFIGS="${CEL_ASSETS_ROOT}/configs"
export CEL_ASSETS_CONFIGS

# Build directory
readonly CEL_ASSETS_BUILD="${CEL_ASSETS_ROOT}/build"
export CEL_ASSETS_BUILD

# celenity assets PATH
readonly CEL_ASSETS_PATH="${CEL_ASSETS_BUILD}/path"
export CEL_ASSETS_PATH

# External sources directory
readonly CEL_ASSETS_EXTERNAL="${CEL_ASSETS_ROOT}/external"
export CEL_ASSETS_EXTERNAL

# External downloads/resources directory
readonly CEL_ASSETS_DOWNLOADS="${CEL_ASSETS_EXTERNAL}/downloads"
export CEL_ASSETS_DOWNLOADS

# Version info
readonly CEL_ASSETS_VERSIONS="${CEL_ASSETS_SCRIPTS}/versions.sh"
export CEL_ASSETS_VERSIONS

# Should we create a log file for get_sources.sh? (Default)
readonly CEL_ASSETS_LOG_SOURCES_DEFAULT=1
if [[ -z "${CEL_ASSETS_LOG_SOURCES+x}" ]]; then
  CEL_ASSETS_LOG_SOURCES="${CEL_ASSETS_LOG_SOURCES_DEFAULT}"
fi
readonly CEL_ASSETS_LOG_SOURCES
export CEL_ASSETS_LOG_SOURCES

# Should we create a log file for push_assets.sh? (Default)
readonly CEL_ASSETS_LOG_PUSH_DEFAULT=1
if [[ -z "${CEL_ASSETS_LOG_PUSH+x}" ]]; then
  CEL_ASSETS_LOG_PUSH="${CEL_ASSETS_LOG_PUSH_DEFAULT}"
fi
readonly CEL_ASSETS_LOG_PUSH
export CEL_ASSETS_LOG_PUSH

# Directory where we should store log files (if logging is desired)
readonly CEL_ASSETS_LOG_DIR_DEFAULT="${CEL_ASSETS_BUILD}/logs"
if [[ -z "${CEL_ASSETS_LOG_DIR+x}" ]]; then
  CEL_ASSETS_LOG_DIR="${CEL_ASSETS_LOG_DIR_DEFAULT}"
fi
readonly CEL_ASSETS_LOG_DIR
export CEL_ASSETS_LOG_DIR

# basename
if [[ "${CEL_ASSETS_OS}" == 'osx' ]]; then
  readonly CEL_ASSETS_BASENAME_DEFAULT='/usr/bin/basename'
else
  readonly CEL_ASSETS_BASENAME_DEFAULT='/bin/basename'
fi
if [[ -z "${CEL_ASSETS_BASENAME+x}" ]]; then
  CEL_ASSETS_BASENAME="${CEL_ASSETS_BASENAME_DEFAULT}"
fi
readonly CEL_ASSETS_BASENAME
export CEL_ASSETS_BASENAME

# cat
readonly CEL_ASSETS_CAT_DEFAULT='/bin/cat'
if [[ -z "${CEL_ASSETS_CAT+x}" ]]; then
  CEL_ASSETS_CAT="${CEL_ASSETS_CAT_DEFAULT}"
fi
readonly CEL_ASSETS_CAT
export CEL_ASSETS_CAT

# chmod
readonly CEL_ASSETS_CHMOD_DEFAULT='/bin/chmod'
if [[ -z "${CEL_ASSETS_CHMOD+x}" ]]; then
  CEL_ASSETS_CHMOD="${CEL_ASSETS_CHMOD_DEFAULT}"
fi
readonly CEL_ASSETS_CHMOD
export CEL_ASSETS_CHMOD

# cp
readonly CEL_ASSETS_CP_DEFAULT='/bin/cp'
if [[ -z "${CEL_ASSETS_CP+x}" ]]; then
  CEL_ASSETS_CP="${CEL_ASSETS_CP_DEFAULT}"
fi
readonly CEL_ASSETS_CP
export CEL_ASSETS_CP

# curl
if [[ "${CEL_ASSETS_OS}" == 'osx' ]]; then
  readonly CEL_ASSETS_CURL_DEFAULT='/opt/homebrew/opt/curl/bin/curl'
else
  readonly CEL_ASSETS_CURL_DEFAULT='/bin/curl'
fi
if [[ -z "${CEL_ASSETS_CURL+x}" ]]; then
  CEL_ASSETS_CURL="${CEL_ASSETS_CURL_DEFAULT}"
fi
readonly CEL_ASSETS_CURL
export CEL_ASSETS_CURL

# dirname
if [[ "${CEL_ASSETS_OS}" == 'osx' ]]; then
  readonly CEL_ASSETS_DIRNAME_DEFAULT='/usr/bin/dirname'
else
  readonly CEL_ASSETS_DIRNAME_DEFAULT='/bin/dirname'
fi
if [[ -z "${CEL_ASSETS_DIRNAME+x}" ]]; then
  CEL_ASSETS_DIRNAME="${CEL_ASSETS_DIRNAME_DEFAULT}"
fi
readonly CEL_ASSETS_DIRNAME
export CEL_ASSETS_DIRNAME

# git
if [[ "${CEL_ASSETS_OS}" == 'osx' ]]; then
  readonly CEL_ASSETS_GIT_DEFAULT='/opt/homebrew/bin/git'
else
  readonly CEL_ASSETS_GIT_DEFAULT='/bin/git'
fi
if [[ -z "${CEL_ASSETS_GIT+x}" ]]; then
  CEL_ASSETS_GIT="${CEL_ASSETS_GIT_DEFAULT}"
fi
readonly CEL_ASSETS_GIT
export CEL_ASSETS_GIT

# GNU awk
if [[ "${CEL_ASSETS_OS}" == 'osx' ]]; then
  readonly CEL_ASSETS_AWK_DEFAULT='/opt/homebrew/bin/gawk'
else
  readonly CEL_ASSETS_AWK_DEFAULT='/bin/awk'
fi
if [[ -z "${CEL_ASSETS_AWK+x}" ]]; then
  CEL_ASSETS_AWK="${CEL_ASSETS_AWK_DEFAULT}"
fi
readonly CEL_ASSETS_AWK
export CEL_ASSETS_AWK

# GNU date
if [[ "${CEL_ASSETS_OS}" == 'osx' ]]; then
  readonly CEL_ASSETS_DATE_DEFAULT='/opt/homebrew/bin/gdate'
else
  readonly CEL_ASSETS_DATE_DEFAULT='/bin/date'
fi
if [[ -z "${CEL_ASSETS_DATE+x}" ]]; then
  CEL_ASSETS_DATE="${CEL_ASSETS_DATE_DEFAULT}"
fi
readonly CEL_ASSETS_DATE
export CEL_ASSETS_DATE

# GNU sed
if [[ "${CEL_ASSETS_OS}" == 'osx' ]]; then
  readonly CEL_ASSETS_SED_DEFAULT='/opt/homebrew/bin/gsed'
else
  readonly CEL_ASSETS_SED_DEFAULT='/bin/sed'
fi
if [[ -z "${CEL_ASSETS_SED+x}" ]]; then
  CEL_ASSETS_SED="${CEL_ASSETS_SED_DEFAULT}"
fi
readonly CEL_ASSETS_SED
export CEL_ASSETS_SED

# GNU tar
if [[ "${CEL_ASSETS_OS}" == 'osx' ]]; then
  readonly CEL_ASSETS_TAR_DEFAULT='/opt/homebrew/bin/gtar'
else
  readonly CEL_ASSETS_TAR_DEFAULT='/bin/tar'
fi
if [[ -z "${CEL_ASSETS_TAR+x}" ]]; then
  CEL_ASSETS_TAR="${CEL_ASSETS_TAR_DEFAULT}"
fi
readonly CEL_ASSETS_TAR
export CEL_ASSETS_TAR

# gzip
if [[ "${CEL_ASSETS_OS}" == 'osx' ]]; then
  readonly CEL_ASSETS_GZIP_DEFAULT='/usr/bin/gzip'
else
  readonly CEL_ASSETS_GZIP_DEFAULT='/bin/gzip'
fi
if [[ -z "${CEL_ASSETS_GZIP+x}" ]]; then
  CEL_ASSETS_GZIP="${CEL_ASSETS_GZIP_DEFAULT}"
fi
readonly CEL_ASSETS_GZIP
export CEL_ASSETS_GZIP

# ln
readonly CEL_ASSETS_LN_DEFAULT='/bin/ln'
if [[ -z "${CEL_ASSETS_LN+x}" ]]; then
  CEL_ASSETS_LN="${CEL_ASSETS_LN_DEFAULT}"
fi
readonly CEL_ASSETS_LN
export CEL_ASSETS_LN

# ls
readonly CEL_ASSETS_LS_DEFAULT='/bin/ls'
if [[ -z "${CEL_ASSETS_LS+x}" ]]; then
  CEL_ASSETS_LS="${CEL_ASSETS_LS_DEFAULT}"
fi
readonly CEL_ASSETS_LS
export CEL_ASSETS_LS

# md5sum
if [[ "${CEL_ASSETS_OS}" == 'osx' ]]; then
  readonly CEL_ASSETS_MD5SUM_DEFAULT='/sbin/md5sum'
else
  readonly CEL_ASSETS_MD5SUM_DEFAULT='/bin/md5sum'
fi
if [[ -z "${CEL_ASSETS_MD5SUM+x}" ]]; then
  CEL_ASSETS_MD5SUM="${CEL_ASSETS_MD5SUM_DEFAULT}"
fi
readonly CEL_ASSETS_MD5SUM
export CEL_ASSETS_MD5SUM

# mkdir
readonly CEL_ASSETS_MKDIR_DEFAULT='/bin/mkdir'
if [[ -z "${CEL_ASSETS_MKDIR+x}" ]]; then
  CEL_ASSETS_MKDIR="${CEL_ASSETS_MKDIR_DEFAULT}"
fi
readonly CEL_ASSETS_MKDIR
export CEL_ASSETS_MKDIR

# rm
readonly CEL_ASSETS_RM_DEFAULT='/bin/rm'
if [[ -z "${CEL_ASSETS_RM+x}" ]]; then
  CEL_ASSETS_RM="${CEL_ASSETS_RM_DEFAULT}"
fi
readonly CEL_ASSETS_RM
export CEL_ASSETS_RM

# sha1sum
if [[ "${CEL_ASSETS_OS}" == 'osx' ]]; then
  readonly CEL_ASSETS_SHA1SUM_DEFAULT='/sbin/sha1sum'
else
  readonly CEL_ASSETS_SHA1SUM_DEFAULT='/bin/sha1sum'
fi
if [[ -z "${CEL_ASSETS_SHA1SUM+x}" ]]; then
  CEL_ASSETS_SHA1SUM="${CEL_ASSETS_SHA1SUM_DEFAULT}"
fi
readonly CEL_ASSETS_SHA1SUM
export CEL_ASSETS_SHA1SUM

# sha256sum
if [[ "${CEL_ASSETS_OS}" == 'osx' ]]; then
  readonly CEL_ASSETS_SHA256SUM_DEFAULT='/sbin/sha256sum'
else
  readonly CEL_ASSETS_SHA256SUM_DEFAULT='/bin/sha256sum'
fi
if [[ -z "${CEL_ASSETS_SHA256SUM+x}" ]]; then
  CEL_ASSETS_SHA256SUM="${CEL_ASSETS_SHA256SUM_DEFAULT}"
fi
readonly CEL_ASSETS_SHA256SUM
export CEL_ASSETS_SHA256SUM

# sha512sum
if [[ "${CEL_ASSETS_OS}" == 'osx' ]]; then
  readonly CEL_ASSETS_SHA512SUM_DEFAULT='/sbin/sha512sum'
else
  readonly CEL_ASSETS_SHA512SUM_DEFAULT='/bin/sha512sum'
fi
if [[ -z "${CEL_ASSETS_SHA512SUM+x}" ]]; then
  CEL_ASSETS_SHA512SUM="${CEL_ASSETS_SHA512SUM_DEFAULT}"
fi
readonly CEL_ASSETS_SHA512SUM
export CEL_ASSETS_SHA512SUM

# tee
if [[ "${CEL_ASSETS_OS}" == 'osx' ]]; then
  readonly CEL_ASSETS_TEE_DEFAULT='/usr/bin/tee'
else
  readonly CEL_ASSETS_TEE_DEFAULT='/bin/tee'
fi
if [[ -z "${CEL_ASSETS_TEE+x}" ]]; then
  CEL_ASSETS_TEE="${CEL_ASSETS_TEE_DEFAULT}"
fi
readonly CEL_ASSETS_TEE
export CEL_ASSETS_TEE

# touch
if [[ "${CEL_ASSETS_OS}" == 'osx' ]]; then
  readonly CEL_ASSETS_TOUCH_DEFAULT='/usr/bin/touch'
else
  readonly CEL_ASSETS_TOUCH_DEFAULT='/bin/touch'
fi
if [[ -z "${CEL_ASSETS_TOUCH+x}" ]]; then
  CEL_ASSETS_TOUCH="${CEL_ASSETS_TOUCH_DEFAULT}"
fi
readonly CEL_ASSETS_TOUCH
export CEL_ASSETS_TOUCH

# uname
if [[ "${CEL_ASSETS_OS}" == 'osx' ]]; then
  readonly CEL_ASSETS_UNAME_DEFAULT='/usr/bin/uname'
else
  readonly CEL_ASSETS_UNAME_DEFAULT='/bin/uname'
fi
if [[ -z "${CEL_ASSETS_UNAME+x}" ]]; then
  CEL_ASSETS_UNAME="${CEL_ASSETS_UNAME_DEFAULT}"
fi
readonly CEL_ASSETS_UNAME
export CEL_ASSETS_UNAME

# unzip
if [[ "${CEL_ASSETS_OS}" == 'osx' ]]; then
  readonly CEL_ASSETS_UNZIP_DEFAULT='/usr/bin/unzip'
else
  readonly CEL_ASSETS_UNZIP_DEFAULT='/bin/unzip'
fi
if [[ -z "${CEL_ASSETS_UNZIP+x}" ]]; then
  CEL_ASSETS_UNZIP="${CEL_ASSETS_UNZIP_DEFAULT}"
fi
readonly CEL_ASSETS_UNZIP
export CEL_ASSETS_UNZIP

# xargs
if [[ "${CEL_ASSETS_OS}" == 'osx' ]]; then
  readonly CEL_ASSETS_XARGS_DEFAULT='/usr/bin/xargs'
else
  readonly CEL_ASSETS_XARGS_DEFAULT='/bin/xargs'
fi
if [[ -z "${CEL_ASSETS_XARGS+x}" ]]; then
  CEL_ASSETS_XARGS="${CEL_ASSETS_XARGS_DEFAULT}"
fi
readonly CEL_ASSETS_XARGS
export CEL_ASSETS_XARGS

# Python
readonly CEL_ASSETS_PYTHON_DIR_DEFAULT="${CEL_ASSETS_EXTERNAL}/python"
if [[ -z "${CEL_ASSETS_PYTHON_DIR+x}" ]]; then
  CEL_ASSETS_PYTHON_DIR="${CEL_ASSETS_PYTHON_DIR_DEFAULT}"
fi
readonly CEL_ASSETS_PYTHON_DIR
export CEL_ASSETS_PYTHON_DIR

# Python (uv) environment
readonly CEL_ASSETS_PYENV_DIR_DEFAULT="${CEL_ASSETS_BUILD}/pyenv"
if [[ -z "${CEL_ASSETS_PYENV_DIR+x}" ]]; then
  CEL_ASSETS_PYENV_DIR="${CEL_ASSETS_PYENV_DIR_DEFAULT}"
fi
readonly CEL_ASSETS_PYENV_DIR
readonly CEL_ASSETS_PYENV="${CEL_ASSETS_PYENV_DIR}/bin/activate"
readonly CEL_ASSETS_PYTHON="${CEL_ASSETS_PYENV_DIR}/bin/python"
export CEL_ASSETS_PYENV
export CEL_ASSETS_PYENV_DIR
export CEL_ASSETS_PYTHON

# s3cmd
readonly CEL_ASSETS_S3CMD_DIR_DEFAULT="${CEL_ASSETS_EXTERNAL}/s3cmd"
if [[ -z "${CEL_ASSETS_S3CMD_DIR+x}" ]]; then
  CEL_ASSETS_S3CMD_DIR="${CEL_ASSETS_S3CMD_DIR_DEFAULT}"
fi
readonly CEL_ASSETS_S3CMD_DIR
readonly CEL_ASSETS_S3CMD="${CEL_ASSETS_PYENV_DIR}/bin/s3cmd"
export CEL_ASSETS_S3CMD
export CEL_ASSETS_S3CMD_DIR

# uv
readonly CEL_ASSETS_UV_DIR_DEFAULT="${CEL_ASSETS_EXTERNAL}/uv"
if [[ -z "${CEL_ASSETS_UV_DIR+x}" ]]; then
  CEL_ASSETS_UV_DIR="${CEL_ASSETS_UV_DIR_DEFAULT}"
fi
readonly CEL_ASSETS_UV_DIR
readonly CEL_ASSETS_UV="${CEL_ASSETS_UV_DIR}/uv"
export CEL_ASSETS_UV
export CEL_ASSETS_UV_DIR

# uv (local directory)
readonly CEL_ASSETS_UV_LOCAL_DEFAULT="${CEL_ASSETS_BUILD}/uv"
if [[ -z "${CEL_ASSETS_UV_LOCAL+x}" ]]; then
  CEL_ASSETS_UV_LOCAL="${CEL_ASSETS_UV_LOCAL_DEFAULT}"
fi
readonly CEL_ASSETS_UV_LOCAL
export CEL_ASSETS_UV_LOCAL

# uv cache
readonly CEL_ASSETS_UV_CACHE_DEFAULT="${CEL_ASSETS_UV_LOCAL}/cache"
if [[ -z "${CEL_ASSETS_UV_CACHE+x}" ]]; then
  CEL_ASSETS_UV_CACHE="${CEL_ASSETS_UV_CACHE_DEFAULT}"
fi
readonly CEL_ASSETS_UV_CACHE
export CEL_ASSETS_UV_CACHE

# uv Python directory
readonly CEL_ASSETS_UV_PYTHON_DEFAULT="${CEL_ASSETS_UV_LOCAL}/python"
if [[ -z "${CEL_ASSETS_UV_PYTHON+x}" ]]; then
  CEL_ASSETS_UV_PYTHON="${CEL_ASSETS_UV_PYTHON_DEFAULT}"
fi
readonly CEL_ASSETS_UV_PYTHON
export CEL_ASSETS_UV_PYTHON

# uv tools
readonly CEL_ASSETS_UV_TOOLS_DEFAULT="${CEL_ASSETS_UV_LOCAL}/tools"
if [[ -z "${CEL_ASSETS_UV_TOOLS+x}" ]]; then
  CEL_ASSETS_UV_TOOLS="${CEL_ASSETS_UV_TOOLS_DEFAULT}"
fi
readonly CEL_ASSETS_UV_TOOLS
export CEL_ASSETS_UV_TOOLS

# Cipher suites
## (These enforce strong cipher suites - see ex. https://browserleaks.com/tls)

## For TLS 1.3 connections
### https://curl.se/docs/manpage.html#--tls13-ciphers
readonly CEL_ASSETS_TLS13_CIPHERS_DEFAULT='TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384'
if [[ -z "${CEL_ASSETS_TLS13_CIPHERS+x}" ]]; then
  CEL_ASSETS_TLS13_CIPHERS="${CEL_ASSETS_TLS13_CIPHERS_DEFAULT}"
fi
readonly CEL_ASSETS_TLS13_CIPHERS
export CEL_ASSETS_TLS13_CIPHERS

## For non-TLS 1.3 connections
### https://curl.se/docs/manpage.html#--ciphers
readonly CEL_ASSETS_NONTLS13_CIPHERS_DEFAULT='ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384'
if [[ -z "${CEL_ASSETS_NONTLS13_CIPHERS+x}" ]]; then
  CEL_ASSETS_NONTLS13_CIPHERS="${CEL_ASSETS_NONTLS13_CIPHERS_DEFAULT}"
fi
readonly CEL_ASSETS_NONTLS13_CIPHERS
export CEL_ASSETS_NONTLS13_CIPHERS

# This includes all ciphers (combining CEL_ASSETS_TLS13_CIPHERS + CEL_ASSETS_NONTLS13_CIPHERS)
## Useful because many programs do not require specifying a separate set of ciphers for TLS 1.3 like curl does
readonly CEL_ASSETS_CIPHERS="${CEL_ASSETS_TLS13_CIPHERS}:${CEL_ASSETS_NONTLS13_CIPHERS}"
export CEL_ASSETS_CIPHERS

# If curl flags are added, this determines whether they should be appended to our default flags (default),
## or if they should override them entirely
readonly CEL_ASSETS_CURL_FLAGS_OVERRIDE_DEFAULT=0
if [[ -z "${CEL_ASSETS_CURL_FLAGS_OVERRIDE+x}" ]]; then
  CEL_ASSETS_CURL_FLAGS_OVERRIDE="${CEL_ASSETS_CURL_FLAGS_OVERRIDE_DEFAULT}"
fi
readonly CEL_ASSETS_CURL_FLAGS_OVERRIDE
export CEL_ASSETS_CURL_FLAGS_OVERRIDE

# curl flags
readonly CEL_ASSETS_CURL_FLAGS_DEFAULT="--disable --no-netrc --ciphers ${CEL_ASSETS_NONTLS13_CIPHERS} --clobber --create-dirs --delegation none --disallow-username-in-url --doh-cert-status --fail --fail-early --junk-session-cookies --no-basic --no-ca-native --no-digest --no-doh-insecure --no-http0.9 --no-insecure --no-negotiate --no-ntlm --no-proxy-basic --no-proxy-ca-native --no-proxy-digest --no-proxy-insecure --no-proxy-ssl-auto-client-cert --no-sessionid --no-ssl-auto-client-cert --no-ssl-no-revoke --no-ssl-revoke-best-effort --no-xattr --parallel --post301 --post302 --post303 --progress-meter --proto -all,https --proto-default https --proto-redir -all,https --proxy-ciphers ${CEL_ASSETS_NONTLS13_CIPHERS} --proxy-tls13-ciphers ${CEL_ASSETS_TLS13_CIPHERS} --referer '' --remove-on-error --retry 5 --retry-all-errors --retry-connrefused --show-error --tls13-ciphers ${CEL_ASSETS_TLS13_CIPHERS} --tlsv1.2 --trace-time --user-agent '' --verbose"
if [[ -z "${CEL_ASSETS_CURL_FLAGS+x}" ]]; then
  CEL_ASSETS_CURL_FLAGS="${CEL_ASSETS_CURL_FLAGS_DEFAULT}"
elif [[ "${CEL_ASSETS_CURL_FLAGS_OVERRIDE}" == 1 ]]; then
  CEL_ASSETS_CURL_FLAGS="${CEL_ASSETS_CURL_FLAGS}"
else
  CEL_ASSETS_CURL_FLAGS="${CEL_ASSETS_CURL_FLAGS_DEFAULT} ${CEL_ASSETS_CURL_FLAGS}"
fi
readonly CEL_ASSETS_CURL_FLAGS
export CEL_ASSETS_CURL_FLAGS

# If s3cmd flags are added, this determines whether they should be appended to our default flags (default),
## or if they should override them entirely
readonly CEL_ASSETS_S3CMD_FLAGS_OVERRIDE_DEFAULT=0
if [[ -z "${CEL_ASSETS_S3CMD_FLAGS_OVERRIDE+x}" ]]; then
  CEL_ASSETS_S3CMD_FLAGS_OVERRIDE="${CEL_ASSETS_S3CMD_FLAGS_OVERRIDE_DEFAULT}"
fi
readonly CEL_ASSETS_S3CMD_FLAGS_OVERRIDE
export CEL_ASSETS_S3CMD_FLAGS_OVERRIDE

# s3cmd flags
readonly CEL_ASSETS_S3CMD_FLAGS_DEFAULT='--check-certificate --check-hostname --check-md5 --no-guess-mime-type --no-mime-magic --progress --ssl'
if [[ -z "${CEL_ASSETS_S3CMD_FLAGS+x}" ]]; then
  CEL_ASSETS_S3CMD_FLAGS="${CEL_ASSETS_S3CMD_FLAGS_DEFAULT}"
elif [[ "${CEL_ASSETS_S3CMD_FLAGS_OVERRIDE}" == 1 ]]; then
  CEL_ASSETS_S3CMD_FLAGS="${CEL_ASSETS_S3CMD_FLAGS}"
else
  CEL_ASSETS_S3CMD_FLAGS="${CEL_ASSETS_S3CMD_FLAGS_DEFAULT} ${CEL_ASSETS_S3CMD_FLAGS}"
fi
readonly CEL_ASSETS_S3CMD_FLAGS
export CEL_ASSETS_S3CMD_FLAGS

# S3

# S3 access key
readonly CEL_ASSETS_S3_ACCESS_KEY_FILE_DEFAULT='/opt/celenity/celenity-assets-s3-access-key.txt'
if [[ -z "${CEL_ASSETS_S3_ACCESS_KEY_FILE+x}" ]]; then
  CEL_ASSETS_S3_ACCESS_KEY_FILE="${CEL_ASSETS_S3_ACCESS_KEY_FILE_DEFAULT}"
fi
readonly CEL_ASSETS_S3_ACCESS_KEY_FILE
export CEL_ASSETS_S3_ACCESS_KEY_FILE

# S3 bucket name
readonly CEL_ASSETS_S3_BUCKET_NAME_FILE_DEFAULT='/opt/celenity/celenity-assets-s3-bucket-name.txt'
if [[ -z "${CEL_ASSETS_S3_BUCKET_NAME_FILE+x}" ]]; then
  CEL_ASSETS_S3_BUCKET_NAME_FILE="${CEL_ASSETS_S3_BUCKET_NAME_FILE_DEFAULT}"
fi
readonly CEL_ASSETS_S3_BUCKET_NAME_FILE
export CEL_ASSETS_S3_BUCKET_NAME_FILE

# S3 endpoint
readonly CEL_ASSETS_S3_ENDPOINT_FILE_DEFAULT='/opt/celenity/celenity-assets-s3-endpoint.txt'
if [[ -z "${CEL_ASSETS_S3_ENDPOINT_FILE+x}" ]]; then
  CEL_ASSETS_S3_ENDPOINT_FILE="${CEL_ASSETS_S3_ENDPOINT_FILE_DEFAULT}"
fi
readonly CEL_ASSETS_S3_ENDPOINT_FILE
export CEL_ASSETS_S3_ENDPOINT_FILE

# S3 secret key
readonly CEL_ASSETS_S3_SECRET_KEY_FILE_DEFAULT='/opt/celenity/celenity-assets-s3-secret-key.txt'
if [[ -z "${CEL_ASSETS_S3_SECRET_KEY_FILE+x}" ]]; then
  CEL_ASSETS_S3_SECRET_KEY_FILE="${CEL_ASSETS_S3_SECRET_KEY_FILE_DEFAULT}"
fi
readonly CEL_ASSETS_S3_SECRET_KEY_FILE
export CEL_ASSETS_S3_SECRET_KEY_FILE

# Set our external environment variables
readonly CEL_ASSETS_ENV_EXTERNAL="${CEL_ASSETS_SCRIPTS}/env_external.sh"
source "${CEL_ASSETS_ENV_EXTERNAL}"

# We've now set our environment variables...
readonly CEL_ASSETS_SET_ENVS=1
export CEL_ASSETS_SET_ENVS
