# celenity assets common environment variables

## CAUTION: Do NOT source this directly!
## Source 'env.sh' instead.

## Additionally, if you need to override any variables here, export them to your shell manually or use `env_override.sh`.
## Do NOT edit this file directly.

# If variables are defined with a custom `env_override.sh` file (located at the root project directory), let's use those
## These need to be set first, to ensure that they don't interfere with certain variables
readonly CEL_ASSETS_ENV_OVERRIDE="${CEL_ASSETS_ROOT}/env_override.sh"
if [[ -f "${CEL_ASSETS_ENV_OVERRIDE}" ]]; then
    source "${CEL_ASSETS_ENV_OVERRIDE}"
fi

# celenity assets

# Scripts directory
readonly CEL_ASSETS_SCRIPTS="${CEL_ASSETS_ROOT}/scripts"
export CEL_ASSETS_SCRIPTS

## celenity assets utilities
readonly CEL_ASSETS_UTILS="${CEL_ASSETS_SCRIPTS}/utilities.sh"
export CEL_ASSETS_UTILS

# Configuration files
readonly CEL_ASSETS_CONFIGS="${CEL_ASSETS_ROOT}/configs"
export CEL_ASSETS_CONFIGS

# Build directory
readonly CEL_ASSETS_BUILD="${CEL_ASSETS_ROOT}/build"
export CEL_ASSETS_BUILD

# External sources directory
readonly CEL_ASSETS_EXTERNAL="${CEL_ASSETS_ROOT}/external"
export CEL_ASSETS_EXTERNAL

# External downloads/resources directory
readonly CEL_ASSETS_DOWNLOADS="${CEL_ASSETS_EXTERNAL}/downloads"
export CEL_ASSETS_DOWNLOADS

# Set our platform, OS, and architecture
readonly CEL_ASSETS_ENV_HELPERS="${CEL_ASSETS_SCRIPTS}/env_helpers.sh"
export CEL_ASSETS_ENV_HELPERS
source "${CEL_ASSETS_ENV_HELPERS}"

# Version info
readonly CEL_ASSETS_VERSIONS="${CEL_ASSETS_SCRIPTS}/versions.sh"
export CEL_ASSETS_VERSIONS

# Should we create a log file for get_sources.sh? (Default)
readonly CEL_ASSETS_LOG_SOURCES_DEFAULT=1
if [[ -z "${CEL_ASSETS_LOG_SOURCES+x}" ]]; then
    CEL_ASSETS_LOG_SOURCES="${CEL_ASSETS_LOG_SOURCES_DEFAULT}"
fi
readonly CEL_ASSETS_LOG_SOURCES
export CEL_ASSETS_LOG_SOURCES

# Should we create a log file for push_assets.sh? (Default)
readonly CEL_ASSETS_LOG_PUSH_DEFAULT=1
if [[ -z "${CEL_ASSETS_LOG_PUSH+x}" ]]; then
    CEL_ASSETS_LOG_PUSH="${CEL_ASSETS_LOG_PUSH_DEFAULT}"
fi
readonly CEL_ASSETS_LOG_PUSH
export CEL_ASSETS_LOG_PUSH

# Directory where we should store log files (if logging is desired)
readonly CEL_ASSETS_LOG_DIR_DEFAULT="${CEL_ASSETS_BUILD}/logs"
if [[ -z "${CEL_ASSETS_LOG_DIR+x}" ]]; then
    CEL_ASSETS_LOG_DIR="${CEL_ASSETS_LOG_DIR_DEFAULT}"
fi
readonly CEL_ASSETS_LOG_DIR
export CEL_ASSETS_LOG_DIR

# GNU awk
if [[ "${CEL_ASSETS_OS}" == 'osx' ]]; then
    readonly CEL_ASSETS_AWK_DEFAULT='gawk'
else
    readonly CEL_ASSETS_AWK_DEFAULT='awk'
fi
if [[ -z "${CEL_ASSETS_AWK+x}" ]]; then
    CEL_ASSETS_AWK="${CEL_ASSETS_AWK_DEFAULT}"
fi
readonly CEL_ASSETS_AWK
export CEL_ASSETS_AWK

# GNU date
if [[ "${CEL_ASSETS_OS}" == 'osx' ]]; then
    readonly CEL_ASSETS_DATE_DEFAULT='gdate'
else
    readonly CEL_ASSETS_DATE_DEFAULT='date'
fi
if [[ -z "${CEL_ASSETS_DATE+x}" ]]; then
    CEL_ASSETS_DATE="${CEL_ASSETS_DATE_DEFAULT}"
fi
readonly CEL_ASSETS_DATE
export CEL_ASSETS_DATE

# GNU sed
if [[ "${CEL_ASSETS_OS}" == 'osx' ]]; then
    readonly CEL_ASSETS_SED_DEFAULT='gsed'
else
    readonly CEL_ASSETS_SED_DEFAULT='sed'
fi
if [[ -z "${CEL_ASSETS_SED+x}" ]]; then
    CEL_ASSETS_SED="${CEL_ASSETS_SED_DEFAULT}"
fi
readonly CEL_ASSETS_SED
export CEL_ASSETS_SED

# GNU tar
if [[ "${CEL_ASSETS_OS}" == 'osx' ]]; then
    readonly CEL_ASSETS_TAR_DEFAULT='gtar'
else
    readonly CEL_ASSETS_TAR_DEFAULT='tar'
fi
if [[ -z "${CEL_ASSETS_TAR+x}" ]]; then
    CEL_ASSETS_TAR="${CEL_ASSETS_TAR_DEFAULT}"
fi
readonly CEL_ASSETS_TAR
export CEL_ASSETS_TAR

# Python
readonly CEL_ASSETS_PYTHON_DIR_DEFAULT="${CEL_ASSETS_EXTERNAL}/python"
if [[ -z "${CEL_ASSETS_PYTHON_DIR+x}" ]]; then
    CEL_ASSETS_PYTHON_DIR="${CEL_ASSETS_PYTHON_DIR_DEFAULT}"
fi
readonly CEL_ASSETS_PYTHON_DIR
export CEL_ASSETS_PYTHON_DIR

# Python (UV) environment
readonly CEL_ASSETS_PYENV_DIR_DEFAULT="${CEL_ASSETS_BUILD}/pyenv"
if [[ -z "${CEL_ASSETS_PYENV_DIR+x}" ]]; then
    CEL_ASSETS_PYENV_DIR="${CEL_ASSETS_PYENV_DIR_DEFAULT}"
fi
readonly CEL_ASSETS_PYENV_DIR
readonly CEL_ASSETS_PYENV="${CEL_ASSETS_PYENV_DIR}/bin/activate"
readonly CEL_ASSETS_PYTHON="${CEL_ASSETS_PYENV_DIR}/bin/python"
export CEL_ASSETS_PYENV
export CEL_ASSETS_PYENV_DIR
export CEL_ASSETS_PYTHON

# s3cmd
readonly CEL_ASSETS_S3CMD_DIR_DEFAULT="${CEL_ASSETS_EXTERNAL}/s3cmd"
if [[ -z "${CEL_ASSETS_S3CMD_DIR+x}" ]]; then
    CEL_ASSETS_S3CMD_DIR="${CEL_ASSETS_S3CMD_DIR_DEFAULT}"
fi
readonly CEL_ASSETS_S3CMD_DIR
readonly CEL_ASSETS_S3CMD="${CEL_ASSETS_PYENV_DIR}/bin/s3cmd"
export CEL_ASSETS_S3CMD
export CEL_ASSETS_S3CMD_DIR

# UV
readonly CEL_ASSETS_UV_DIR_DEFAULT="${CEL_ASSETS_EXTERNAL}/uv"
if [[ -z "${CEL_ASSETS_UV_DIR+x}" ]]; then
    CEL_ASSETS_UV_DIR="${CEL_ASSETS_UV_DIR_DEFAULT}"
fi
readonly CEL_ASSETS_UV_DIR
readonly CEL_ASSETS_UV="${CEL_ASSETS_UV_DIR}/uv"
export CEL_ASSETS_UV
export CEL_ASSETS_UV_DIR

# UV (local directory)
readonly CEL_ASSETS_UV_LOCAL_DEFAULT="${CEL_ASSETS_BUILD}/uv"
if [[ -z "${CEL_ASSETS_UV_LOCAL+x}" ]]; then
    CEL_ASSETS_UV_LOCAL="${CEL_ASSETS_UV_LOCAL_DEFAULT}"
fi
readonly CEL_ASSETS_UV_LOCAL
export CEL_ASSETS_UV_LOCAL

# UV cache
readonly CEL_ASSETS_UV_CACHE_DEFAULT="${CEL_ASSETS_UV_LOCAL}/cache"
if [[ -z "${CEL_ASSETS_UV_CACHE+x}" ]]; then
    CEL_ASSETS_UV_CACHE="${CEL_ASSETS_UV_CACHE_DEFAULT}"
fi
readonly CEL_ASSETS_UV_CACHE
export CEL_ASSETS_UV_CACHE

# UV Python directory
readonly CEL_ASSETS_UV_PYTHON_DEFAULT="${CEL_ASSETS_UV_LOCAL}/python"
if [[ -z "${CEL_ASSETS_UV_PYTHON+x}" ]]; then
    CEL_ASSETS_UV_PYTHON="${CEL_ASSETS_UV_PYTHON_DEFAULT}"
fi
readonly CEL_ASSETS_UV_PYTHON
export CEL_ASSETS_UV_PYTHON

# UV tools
readonly CEL_ASSETS_UV_TOOLS_DEFAULT="${CEL_ASSETS_UV_LOCAL}/tools"
if [[ -z "${CEL_ASSETS_UV_TOOLS+x}" ]]; then
    CEL_ASSETS_UV_TOOLS="${CEL_ASSETS_UV_TOOLS_DEFAULT}"
fi
readonly CEL_ASSETS_UV_TOOLS
export CEL_ASSETS_UV_TOOLS

# Cipher suites
## (This enforces strong cipher suites - see ex. https://browserleaks.com/tls)
readonly CEL_ASSETS_CIPHERS_DEFAULT='TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384'
if [[ -z "${CEL_ASSETS_CIPHERS+x}" ]]; then
    CEL_ASSETS_CIPHERS="${CEL_ASSETS_CIPHERS_DEFAULT}"
fi
readonly CEL_ASSETS_CIPHERS
export CEL_ASSETS_CIPHERS

# If curl flags are added, this determines whether they should be appended to our default flags (default),
## or if they should override them entirely
readonly CEL_ASSETS_CURL_FLAGS_OVERRIDE_DEFAULT=0
if [[ -z "${CEL_ASSETS_CURL_FLAGS_OVERRIDE+x}" ]]; then
    CEL_ASSETS_CURL_FLAGS_OVERRIDE="${CEL_ASSETS_CURL_FLAGS_OVERRIDE_DEFAULT}"
fi
readonly CEL_ASSETS_CURL_FLAGS_OVERRIDE
export CEL_ASSETS_CURL_FLAGS_OVERRIDE

# curl flags
readonly CEL_ASSETS_CURL_FLAGS_DEFAULT="-q --disable --no-netrc -j -e "" -A "" -S --ciphers ${CEL_ASSETS_CIPHERS} --clobber --create-dirs --delegation none --disallow-username-in-url --doh-cert-status --ftp-create-dirs --ftp-ssl-control --junk-session-cookies --no-basic --no-ca-native --no-digest --no-doh-insecure --no-http0.9 --no-insecure --no-proxy-insecure --no-negotiate --no-ntlm --no-proxy-basic --no-proxy-ca-native --no-proxy-digest --no-proxy-insecure --no-proxy-ntlm --no-proxy-ssl-allow-beast --no-proxy-ssl-auto-client-cert --no-sessionid --no-skip-existing --no-ssl --no-ssl-allow-beast --no-ssl-auto-client-cert --no-ssl-no-revoke --no-ssl-revoke-best-effort --no-tls-earlydata --no-xattr --progress-meter --proto -all,https --proto-default https --proto-redir -all,https --referer "" --remove-on-error --show-error --ssl-reqd --tlsv1.2 --trace-time --user-agent "" --verbose"
if [[ -z "${CEL_ASSETS_CURL_FLAGS+x}" ]]; then
    CEL_ASSETS_CURL_FLAGS="${CEL_ASSETS_CURL_FLAGS_DEFAULT}"
elif [[ "${CEL_ASSETS_CURL_FLAGS_OVERRIDE}" == 1 ]]; then
    CEL_ASSETS_CURL_FLAGS="${CEL_ASSETS_CURL_FLAGS}"
else
    CEL_ASSETS_CURL_FLAGS="${CEL_ASSETS_CURL_FLAGS_DEFAULT} ${CEL_ASSETS_CURL_FLAGS}"
fi
readonly CEL_ASSETS_CURL_FLAGS
export CEL_ASSETS_CURL_FLAGS

# If s3cmd flags are added, this determines whether they should be appended to our default flags (default),
## or if they should override them entirely
readonly CEL_ASSETS_S3CMD_FLAGS_OVERRIDE_DEFAULT=0
if [[ -z "${CEL_ASSETS_S3CMD_FLAGS_OVERRIDE+x}" ]]; then
    CEL_ASSETS_S3CMD_FLAGS_OVERRIDE="${CEL_ASSETS_S3CMD_FLAGS_OVERRIDE_DEFAULT}"
fi
readonly CEL_ASSETS_S3CMD_FLAGS_OVERRIDE
export CEL_ASSETS_S3CMD_FLAGS_OVERRIDE

# s3cmd flags
readonly CEL_ASSETS_S3CMD_FLAGS_DEFAULT='--check-certificate --check-hostname --check-md5 --progress --ssl'
if [[ -z "${CEL_ASSETS_S3CMD_FLAGS+x}" ]]; then
    CEL_ASSETS_S3CMD_FLAGS="${CEL_ASSETS_S3CMD_FLAGS_DEFAULT}"
elif [[ "${CEL_ASSETS_S3CMD_FLAGS_OVERRIDE}" == 1 ]]; then
    CEL_ASSETS_S3CMD_FLAGS="${CEL_ASSETS_S3CMD_FLAGS}"
else
    CEL_ASSETS_S3CMD_FLAGS="${CEL_ASSETS_S3CMD_FLAGS_DEFAULT} ${CEL_ASSETS_S3CMD_FLAGS}"
fi
readonly CEL_ASSETS_S3CMD_FLAGS
export CEL_ASSETS_S3CMD_FLAGS

# S3

# S3 access key
readonly CEL_ASSETS_S3_ACCESS_KEY_FILE_DEFAULT='/opt/celenity/celenity-assets-s3-access-key.txt'
if [[ -z "${CEL_ASSETS_S3_ACCESS_KEY_FILE+x}" ]]; then
    CEL_ASSETS_S3_ACCESS_KEY_FILE="${CEL_ASSETS_S3_ACCESS_KEY_FILE_DEFAULT}"
fi
readonly CEL_ASSETS_S3_ACCESS_KEY_FILE
export CEL_ASSETS_S3_ACCESS_KEY_FILE

# S3 bucket name
readonly CEL_ASSETS_S3_BUCKET_NAME_FILE_DEFAULT='/opt/celenity/celenity-assets-s3-bucket-name.txt'
if [[ -z "${CEL_ASSETS_S3_BUCKET_NAME_FILE+x}" ]]; then
    CEL_ASSETS_S3_BUCKET_NAME_FILE="${CEL_ASSETS_S3_BUCKET_NAME_FILE_DEFAULT}"
fi
readonly CEL_ASSETS_S3_BUCKET_NAME_FILE
export CEL_ASSETS_S3_BUCKET_NAME_FILE

# S3 endpoint
readonly CEL_ASSETS_S3_ENDPOINT_FILE_DEFAULT='/opt/celenity/celenity-assets-s3-endpoint.txt'
if [[ -z "${CEL_ASSETS_S3_ENDPOINT_FILE+x}" ]]; then
    CEL_ASSETS_S3_ENDPOINT_FILE="${CEL_ASSETS_S3_ENDPOINT_FILE_DEFAULT}"
fi
readonly CEL_ASSETS_S3_ENDPOINT_FILE
export CEL_ASSETS_S3_ENDPOINT_FILE

# S3 secret key
readonly CEL_ASSETS_S3_SECRET_KEY_FILE_DEFAULT='/opt/celenity/celenity-assets-s3-secret-key.txt'
if [[ -z "${CEL_ASSETS_S3_SECRET_KEY_FILE+x}" ]]; then
    CEL_ASSETS_S3_SECRET_KEY_FILE="${CEL_ASSETS_S3_SECRET_KEY_FILE_DEFAULT}"
fi
readonly CEL_ASSETS_S3_SECRET_KEY_FILE
export CEL_ASSETS_S3_SECRET_KEY_FILE

# Set our external environment variables
readonly CEL_ASSETS_ENV_EXTERNAL="${CEL_ASSETS_SCRIPTS}/env_external.sh"
source "${CEL_ASSETS_ENV_EXTERNAL}"

# We've now set our environment variables...
readonly CEL_ASSETS_SET_ENVS=1
export CEL_ASSETS_SET_ENVS
